workflows:
  ios-workflow:
    name: iOS Build
    max_build_duration: 60
    environment:
      xcode: latest
      cocoapods: default
    scripts:
      - name: Install CocoaPods
        script: pod install
      - name: Build iOS
        script: |
          xcodebuild \
            -workspace PB-KYC.xcworkspace \
            -scheme PB-KYC \
            -configuration Release \
            -sdk iphoneos \
            CODE_SIGNING_ALLOWED=NO \
            CODE_SIGNING_REQUIRED=NO \
            build
    artifacts:
      - build/**/*.ipa
